on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          sstc/headful-chromium
        tags: |
          type=raw,value=latest
          type=raw,value=ubuntu
          type=raw,value=ubuntu-24
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./debian-11/Dockerfile
        tags: sstc/headful-chromium:debian-11
    - uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./debian-12/Dockerfile
        tags: sstc/headful-chromium:debian-12
    - uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./ubuntu-20/Dockerfile
        tags: sstc/headful-chromium:ubuntu-20
    - uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./ubuntu-22/Dockerfile
        tags: sstc/headful-chromium:ubuntu-22
    - uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        file: ./ubuntu-24/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
    - uses: actions/checkout@v4
    - uses: christian-korneck/update-container-description-action@v1
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
      with:
        destination_container_repo: sstc/headful-chromium
        short_description: https://github.com/${{ github.repository }}
    - uses: up9cloud/action-notify@master
      if: cancelled() == false
      env:
        GITHUB_JOB_STATUS: ${{ job.status }}
        TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
        TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
